security:
  providers:
    app_user_provider:
      entity:
        class: App\Module\Auth\V1\Domain\Entity\AuthUser
        property: token
  firewalls:
    main:
      lazy: true
      stateless: true
      provider: app_user_provider
      entry_point: App\Core\Security\AuthenticationEntryPoint
      access_denied_handler: App\Core\Security\AccessDeniedHandler
      custom_authenticators:
        - App\Core\Security\AccessTokenHandler
  access_control:
    - { path: ^/api/v1/auth/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/v1, roles: IS_AUTHENTICATED_FULLY }