version: '3'

services:
  nginx:
    container_name: app_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 443:443
      - 80:80
    links:
      - fpm
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    depends_on:
      - fpm
      - mysql
    networks:
      - app-network
  fpm:
    container_name: app_fpm
    env_file:
      - .env
    build:
      context: ./
      dockerfile: docker/fpm/Dockerfile
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    links:
      - mysql
    networks:
      - app-network

  mysql:
    container_name: app_mysql
    image: mysql:8.0.30
    restart: always
    tty: true
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  db_data: